spring:
  datasource:
    url: jdbc:h2:mem:accountdb
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080