spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  sleuth:
    sampler:
      probability: 0.1
  zipkin:
    baseUrl: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Gateway Server Microservice
    description: Huseyin Ocal Gateway Server Application
    version: 1.0.0

logging:
  level:
    huseyinocal:
      gatewayserver: DEBUG
