spring:
  application:
    name: card

  datasource:
    url: jdbc:h2:mem:carddb
    username: sa
    password:

  profiles:
    active: default

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  config:
    import: optional:configserver:http://localhost:8071

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"