global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'account'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account:8080']
  - job_name: 'loan'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['loan:8090']
  - job_name: 'card'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['card:9000']
