version: "3.8"

services:

  configserver:
    image: huseyinocal/config-server:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - huseyinocal-network

  accounts:
    image: huseyinocal/account:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - huseyinocal-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: huseyinocal/loan:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - huseyinocal-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: huseyinocal/card:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - huseyinocal-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  huseyinocal-network:  