spring:
  application:
    name: configserver

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/huseyinocal035/microservice-eb-config.git
          clone-on-start: true
          default-label: master
#        native:
          # to get configuration from classpath
#          search-locations: classpath:/config
          # to get configuration from file system
#          search-locations: file:///C://config

  sleuth:
    sampler:
      probability: 0.1
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8071

encrypt:
  key: encrypt-key
