spring:
  application:
    name: configserver

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/huseyinocal035/microservice-eb-config.git
          clone-on-start: true
          default-label: master
#        native:
          # to get configuration from classpath
#          search-locations: classpath:/config
          # to get configuration from file system
#          search-locations: file:///C://config

server:
  port: 8071

encrypt:
  key: F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9y$B&E)H@McQfTjWnZr4t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWnZr4u7
